config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  devise_for :users
  # get 'site/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "site#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string           not null
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_uploads_on_title    (title)
#  index_uploads_on_user_id  (user_id)
#

class Upload < ApplicationRecord
  has_one_attached :file, dependent: :destroy

  validates_presence_of :title

  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  full_name              :string           not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates_presence_of :full_name

  has_many :uploads, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :config_devise_params, if: :devise_controller?

  protected

  def config_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[
                                        full_name
                                        email
                                        password
                                        password_confirmation
                                      ])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /uploads or /uploads.json
  def index
    @uploads = current_user.uploads.all
  end

  # GET /uploads/1 or /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads or /uploads.json
  def create
    @upload = current_user.uploads.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to upload_url(@upload), notice: "Upload was successfully created." }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1 or /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to upload_url(@upload), notice: "Upload was successfully updated." }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1 or /uploads/1.json
  def destroy
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url, notice: "Upload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])

      if @upload.user != current_user
        redirect_to uploads_url, notice: "You are not authorized to view this page."
      end
    end

    # Only allow a list of trusted parameters through.
    def upload_params
      params.require(:upload).permit(:title, :description, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myfiles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/notifications" %>
    <div class="container mt-5">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_url %>">MyFiles</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="<%= root_path %>">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_upload_url %>">Upload File</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= uploads_url %>">All Files</a>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <span class="nav-link text-black">Welcome <%= current_user.full_name %>!</span>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, class: "nav-link", data: { "turbo-method": :delete } %>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_url %>">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_url %>">Sign up</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_notifications.html.erb
<% if notice || alert %>
<div class="container-fluid">
  <div class="row">
    <% if notice %>
      <div class="col alert alert-primary rounded-0"><%= notice %></div>
    <% elsif alert %>
    <div class="col alert alert-danger rounded-0"><%= alert %></div>
    <% end %>
  </div>
</div>
<% end %>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/uploads/_form.html.erb
<%= simple_form_for(@upload) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :file, as: :file, required: true %>
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary my-2" %>
  </div>
<% end %>

app/views/uploads/_upload.html.erb
<div id="<%= dom_id upload %>">
  <p>
    Title:
    <%= link_to upload.title, url_for(upload.file), target: :blank %>
  </p>
  <p>
    Sharable Url: <%= URI.parse(root_url) + url_for(upload.file) %>
  </p>
  <% unless upload.description.blank? %>
    <p>
      <strong>Description:</strong>
      <%= upload.description %>
    </p>
  <% end %>
</div>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render "form", upload: @upload %>

<br>

<div>
  <%= link_to "Show this upload", @upload %> |
  <%= link_to "Back to uploads", uploads_path %>
</div>

app/views/uploads/index.html.erb
<h2 class="mb-5 border-bottom pb-2">Uploads</h2>

<div id="uploads">
  <% @uploads.each do |upload| %>
    <div class="d-flex justify-content-between border-bottom mb-5">
      <%= render upload %>
      <p>
        <%= link_to "Show this upload", upload %>
      </p>
    </div>

  <% end %>
</div>

<%= link_to "New upload", new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render "form", upload: @upload %>

<br>

<div>
  <%= link_to "Back to uploads", uploads_path %>
</div>

app/views/uploads/show.html.erb
<%= render @upload %>

<div>
  <%= link_to "Edit this upload", edit_upload_path(@upload), class: "btn btn-primary" %>
  <%= link_to "Back to uploads", uploads_path, class: 'btn btn-primary' %>

  <%= link_to "Destroy this upload", @upload, method: :delete, class: 'btn btn-danger my-2 display-inline' %>
</div>